### ISSUE TITLE
Default font size too small

### ISSUE THREAD

**Issue by rikhuijzer** [tlienart/FranklinTemplates.jl#102]
Google Search Console gave me a warning that some text on my website was too small for mobile devices. This got me down a bit of a rabbit hole and I found <https://learnui.design/blog/mobile-desktop-website-font-size-guidelines.html>.

This article states that the default of 16px is okay for interaction-heavy pages, but should usually be higher for text-heavy pages. Medium goes to 21px even (I've checked)! For example, compare the small text sizes (desktop size; mobile size) for
- https://julialang.org/blog/2020/09/juliacon-2020-open-source-bof-follow-up/ (100%, so 16px?)
- https://franklinjl.org/ (15px; 15px)
with the bigger ones at
- https://oferka.medium.com/playmaker-the-reality-of-10x-engineer-8af96abce74 (21px; 18px)
- https://huijzer.xyz/posts/grades-queries/ (19px; 19px)

I find the larger ones much more pleasant to read on both desktop and mobile (or at least on desktop it means that I don't have to bump up the font size like always). On the phone, the bigger text also is comparable to most books I could find here and still smaller than some of the books such as David Goggins - Can't Hurt Me. 

So, how about bumping the default up for Franklin to 19px? I would go to 20px, but the code is then not fully visible on smartphone when holding it to the side. If you agree, then I'll walk through the templates and fix the then messed up spacing and title sizes.

**Comment by tlienart** [comment]
Haha great!! So font size you can change for all templates in one shot more or less via the common/css; but I recommend you build the website with all templates locally to check that they all look ok (happy to do that too).

In any case while I'm in favour of having a larger default, at the moment the code is proportional to it if I'm not mistaken (something like 90%, should check), I think the current font size for code is fine, so that will have to be adjusted.

Hmmm... maybe adjust it for your website, then suggest a PR for everything, we discuss, and if it looks good only for some templates then we adjust for those templates and that's it :-)

Thanks for looking into this!

**Comment by rikhuijzer** [comment]
> In any case while I'm in favour of having a larger default, at the moment the code is proportional to it if I'm not mistaken (something like 90%, should check), I think the current font size for code is fine, so that will have to be adjusted.

I didn't even think of making the code smaller, but it makes a lot of sense!

> Hmmm... maybe adjust it for your website, then suggest a PR for everything, we discuss, and if it looks good only for some templates then we adjust for those templates and that's it :-)

Yas, will do. I expect to send in a first draft PR before Sunday evening.

**Comment by tlienart** [comment]
I think this  can  now be closed thanks to your great work :)
